sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.5

env:
  global:
    - MO_ADDRESS=localhost:20000
    - MONGO_ORCHESTRATION_HOME=$PWD
  matrix:
    #- MONGODB=2.4.14
    #- MONGODB=2.6.12
    #- MONGODB=3.0.12
    - MONGODB=3.2.10
    #- MONGODB=3.4.0-rc0

matrix:
  fast_finish: true

install:
  - pip install pymongo==2.9
  - pip install "mongo-orchestration>=0.6,<1.0"
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar zxf mongodb-linux-x86_64-${MONGODB}.tgz
  - export PATH=${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/:${PATH}
  - mongod --version

before_script:
  - mongo-orchestration start -p 20000

script:
  - curl ${MO_ADDRESS}
  - pip install .
  - pip install requests
  - python launch.py

after_script:
  - mongo-orchestration stop
  - cat ${MONGO_ORCHESTRATION_HOME}/server.log
