language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install pymongo==2.9
  - pip install mongo-orchestration==0.3.1
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.3 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - sudo apt-get update
  - sudo apt-cache madison mongodb-org-server
  - sudo apt-get install -y mongodb-org=3.4-rc0 mongodb-org-server=3.4-rc0 mongodb-org-shell=3.4-rc0 mongodb-org-mongos=3.4-rc0 mongodb-org-tools=3.4-rc0

before_script:
  - mongo-orchestration start

script:
  - python setup.py test

after_script:
  - mongo-orchestration stop
