language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install pymongo==2.9
  - pip install "mongo-orchestration>=0.6,<1.0"
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1204-3.4.0-rc0.tgz
  - tar zxf mongodb-linux-x86_64-ubuntu1204-3.4.0-rc0.tgz
  - which mongod
  - mongod --version
  - sudo cp mongodb-linux-x86_64-ubuntu1204-3.4.0-rc0/bin/* /usr/bin/
  - which mongod
  - mongod --version

before_script:
  - mongo-orchestration start

script:
  - python setup.py test

after_script:
  - mongo-orchestration stop
