language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.5

env:
  matrix:
    - MONGODB=2.4.14
    - MONGODB=2.6.12
    - MONGODB=3.0.12
    - MONGODB=3.2.10
    - MONGODB=3.4.0-rc0

install:
  - pip install pymongo==2.9
  - pip install "mongo-orchestration>=0.6,<1.0"
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar zxf mongodb-linux-x86_64-${MONGODB}.tgz
  - sudo cp mongodb-linux-x86_64-${MONGODB}/bin/* /usr/bin/
  - mongod --version

before_script:
  - mongo-orchestration start

script:
  - python setup.py test

after_script:
  - mongo-orchestration stop
